name: Publish

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: KCL Publish
        uses: docker://kcllang/kcl
        env:
          KPM_REG: ghcr.io
          KPM_REPO: ${{ github.repository }}
        with:
          args: kcl registry login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ${{ secrets.REG }} && kcl mod push
